-- Seed countries data for World Vision International website

INSERT INTO countries (name, slug, region, description, overview, key_results, focus_areas, featured) VALUES
-- Africa
('Nigeria', 'nigeria', 'Africa', 'Supporting economic growth and sustainable development across Nigeria.', 'World Vision International has been working in Nigeria since 1965, supporting the government and people in their development efforts. Our work focuses on economic diversification, job creation, and building resilient communities.', ARRAY['2.5 million jobs created', '500+ SMEs supported', '$1.2B in investments mobilized'], ARRAY['Economic Diversification', 'Youth Employment', 'Climate Resilience'], true),
('Kenya', 'kenya', 'Africa', 'Partnering with Kenya on sustainable economic transformation.', 'In Kenya, World Vision International supports inclusive economic growth through innovation, digital transformation, and sustainable finance initiatives.', ARRAY['1.8 million beneficiaries', '300 startups funded', '45% increase in digital inclusion'], ARRAY['Digital Economy', 'Green Finance', 'Agricultural Development'], true),
('Ethiopia', 'ethiopia', 'Africa', 'Building foundations for long-term economic prosperity.', 'World Vision International Ethiopia focuses on agricultural modernization, industrial development, and human capital investment.', ARRAY['3 million farmers reached', '200+ cooperatives strengthened', '$500M in agricultural exports'], ARRAY['Agriculture', 'Manufacturing', 'Education'], false),
('South Africa', 'south-africa', 'Africa', 'Advancing inclusive growth and economic transformation.', 'In South Africa, we support economic inclusion, enterprise development, and green transition initiatives.', ARRAY['100,000 entrepreneurs supported', '250MW renewable capacity', '15% reduction in inequality'], ARRAY['Enterprise Development', 'Clean Energy', 'Skills Development'], true),
('Ghana', 'ghana', 'Africa', 'Supporting Ghana''s journey to middle-income status.', 'UNEDF Ghana works on economic governance, private sector development, and sustainable natural resource management.', ARRAY['$800M in FDI facilitated', '50,000 jobs in extractives', 'Improved fiscal transparency'], ARRAY['Governance', 'Natural Resources', 'Trade Facilitation'], false),
('Tanzania', 'tanzania', 'Africa', 'Empowering communities through economic development.', 'Our work in Tanzania focuses on agricultural value chains, tourism development, and infrastructure investment.', ARRAY['2 million smallholders supported', '30% tourism growth', '500km roads built'], ARRAY['Agriculture', 'Tourism', 'Infrastructure'], false),

-- Asia & Pacific
('India', 'india', 'Asia & Pacific', 'Collaborating on India''s sustainable development journey.', 'UNEDF India works across multiple states to support inclusive growth, climate action, and digital transformation.', ARRAY['10 million lives improved', '5GW solar capacity supported', '1000+ villages digitized'], ARRAY['Renewable Energy', 'Digital India', 'Rural Development'], true),
('Bangladesh', 'bangladesh', 'Asia & Pacific', 'Supporting Bangladesh''s remarkable development story.', 'In Bangladesh, we focus on economic diversification, climate adaptation, and women''s economic empowerment.', ARRAY['5 million women empowered', '$2B climate finance mobilized', '40% poverty reduction'], ARRAY['Women''s Empowerment', 'Climate Adaptation', 'Garment Industry'], true),
('Indonesia', 'indonesia', 'Asia & Pacific', 'Partnering for sustainable archipelago development.', 'UNEDF Indonesia supports green growth, maritime economy, and decentralized development initiatives.', ARRAY['3 million hectares protected', '200 islands connected', '25% marine economy growth'], ARRAY['Blue Economy', 'Forest Conservation', 'Island Development'], false),
('Vietnam', 'vietnam', 'Asia & Pacific', 'Advancing Vietnam''s integration into the global economy.', 'Our work supports Vietnam''s transition to a market economy, FDI attraction, and sustainable industrialization.', ARRAY['$5B FDI supported', '2 million jobs in manufacturing', '98% electrification rate'], ARRAY['Manufacturing', 'Trade', 'Energy Access'], false),
('Philippines', 'philippines', 'Asia & Pacific', 'Building resilient communities and economies.', 'UNEDF Philippines focuses on disaster resilience, SME development, and overseas worker support.', ARRAY['1 million families resilient', '50,000 SMEs strengthened', '$1B remittance efficiency'], ARRAY['Disaster Resilience', 'SME Development', 'Migration'], false),
('Afghanistan', 'afghanistan', 'Asia & Pacific', 'Providing essential economic support during crisis.', 'In Afghanistan, UNEDF provides humanitarian assistance while maintaining basic economic services and livelihood support.', ARRAY['3 million people assisted', 'Basic services maintained', 'Women''s livelihoods protected'], ARRAY['Humanitarian Response', 'Livelihoods', 'Basic Services'], true),

-- Europe & CIS
('Ukraine', 'ukraine', 'Europe & CIS', 'Supporting recovery and reconstruction efforts.', 'UNEDF Ukraine focuses on economic recovery, infrastructure rehabilitation, and business continuity support.', ARRAY['$500M recovery support', '10,000 businesses assisted', '50,000 jobs preserved'], ARRAY['Recovery', 'Infrastructure', 'Business Support'], true),
('Georgia', 'georgia', 'Europe & CIS', 'Facilitating economic modernization and EU integration.', 'Our work supports Georgia''s economic reforms, SME development, and regional trade integration.', ARRAY['30% export growth', '5,000 SMEs digitized', 'Improved business environment'], ARRAY['EU Integration', 'SME Development', 'Trade'], false),
('Moldova', 'moldova', 'Europe & CIS', 'Building economic resilience and diversification.', 'UNEDF Moldova supports energy security, agricultural modernization, and diaspora engagement.', ARRAY['40% energy independence', '100,000 farmers trained', '$200M diaspora investment'], ARRAY['Energy Security', 'Agriculture', 'Diaspora'], false),
('Uzbekistan', 'uzbekistan', 'Europe & CIS', 'Supporting economic liberalization and reform.', 'Our work in Uzbekistan focuses on market reforms, private sector development, and regional connectivity.', ARRAY['50% private sector growth', '200,000 new businesses', 'Regional trade doubled'], ARRAY['Market Reforms', 'Private Sector', 'Connectivity'], false),

-- Arab States
('Jordan', 'jordan', 'Arab States', 'Building economic resilience in challenging conditions.', 'UNEDF Jordan supports economic diversification, refugee integration, and youth employment.', ARRAY['500,000 refugees supported', '100,000 youth employed', '20% water efficiency'], ARRAY['Refugee Integration', 'Youth Employment', 'Water Security'], true),
('Egypt', 'egypt', 'Arab States', 'Supporting Egypt''s economic modernization.', 'Our work focuses on sustainable cities, renewable energy, and inclusive finance.', ARRAY['5 million urban residents', '3GW solar capacity', '2 million microloans'], ARRAY['Urban Development', 'Renewable Energy', 'Microfinance'], true),
('Lebanon', 'lebanon', 'Arab States', 'Providing critical support during economic crisis.', 'UNEDF Lebanon delivers emergency economic assistance while supporting longer-term recovery planning.', ARRAY['1 million people assisted', 'Essential services maintained', 'Recovery plan developed'], ARRAY['Crisis Response', 'Basic Services', 'Recovery Planning'], false),
('Iraq', 'iraq', 'Arab States', 'Supporting stabilization and economic recovery.', 'Our work in Iraq focuses on reconstruction, job creation, and economic governance.', ARRAY['500,000 jobs created', '$1B infrastructure rebuilt', 'Improved fiscal management'], ARRAY['Reconstruction', 'Employment', 'Governance'], false),

-- Latin America & Caribbean
('Brazil', 'brazil', 'Latin America', 'Advancing sustainable development in the Amazon and beyond.', 'UNEDF Brazil works on Amazon conservation, social inclusion, and green economy transition.', ARRAY['10 million hectares protected', '2 million families supported', '30% deforestation reduction'], ARRAY['Amazon Conservation', 'Social Protection', 'Green Economy'], true),
('Colombia', 'colombia', 'Latin America', 'Supporting peace and sustainable development.', 'Our work supports Colombia''s peace process through economic reintegration and rural development.', ARRAY['50,000 ex-combatants reintegrated', '200 municipalities supported', '$500M peace dividends'], ARRAY['Peace Building', 'Rural Development', 'Reintegration'], true),
('Mexico', 'mexico', 'Latin America', 'Partnering on inclusive and sustainable growth.', 'UNEDF Mexico focuses on inequality reduction, climate action, and innovation ecosystems.', ARRAY['3 million beneficiaries', '40% emissions reduction plan', '500 startups supported'], ARRAY['Inequality', 'Climate Action', 'Innovation'], false),
('Haiti', 'haiti', 'Latin America', 'Providing essential support for development and recovery.', 'In Haiti, UNEDF delivers humanitarian assistance while building foundations for long-term development.', ARRAY['2 million people assisted', 'Basic services restored', 'Local capacity built'], ARRAY['Humanitarian Response', 'Basic Services', 'Capacity Building'], false),
('Peru', 'peru', 'Latin America', 'Supporting inclusive growth and environmental sustainability.', 'Our work in Peru focuses on extractives governance, biodiversity conservation, and indigenous rights.', ARRAY['$1B mining revenues improved', '5 million hectares conserved', '100 indigenous communities supported'], ARRAY['Extractives', 'Biodiversity', 'Indigenous Rights'], false)

ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  region = EXCLUDED.region,
  description = EXCLUDED.description,
  overview = EXCLUDED.overview,
  key_results = EXCLUDED.key_results,
  focus_areas = EXCLUDED.focus_areas,
  featured = EXCLUDED.featured,
  updated_at = NOW();
